- name: Remove v2plugin rootfs directory
  file: state=absent path=/var/lib/v2plugin/rootfs

- name: Create v2plugin rootfs directory
  file: state=directory path=/var/lib/v2plugin/rootfs

- name: Unpack v2plugin from local archive
  unarchive:
    src: "/var/contiv_cache/{{ contiv_v2plugin_tar_filename }}"
    dest: /var/lib/v2plugin/rootfs/

- name: Copy config.json for plugin container
  copy: src=/var/contiv_cache/config.json dest=/var/lib/v2plugin

- name: Create v2plugin from exploded archive
  shell: >
    docker plugin create {{ contiv_v2plugin_image }} /var/lib/v2plugin/

- name: Set v2plugin settings
  shell: >
    docker plugin set {{ contiv_v2plugin_image }}
    ctrl_ip={{ node_addr }}
    control_url={{ node_addr }}:{{ netmaster_port }}
    vxlan_port={{ vxlan_port }}
    iflist={{ netplugin_if }}
    plugin_name={{ contiv_v2plugin_image }}
    cluster_store={{ cluster_store }}
    plugin_role={{ run_as }}
    fwd_mode={{ fwd_mode }}

- name: Remove v2plugin rootfs
  file: state=absent path=/var/lib/v2plugin/rootfs

- name: Remove v2plugin config.json
  file: state=absent path=/var/lib/v2plugin/config.json

- name: start v2plugin
  systemd: name=v2plugin state=started
